import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import { COMPANY_ID } from '../../support/fixture.js';
import {
  authoriseRefundAtExposure,
  authorisePause,
  authoriseReship,
  authoriseRefund,
  claimJournalRows,
  createOutboxHarness,
  outboxRows,
  type AuthorisedEffect,
  type OutboxHarness,
} from '../../support/outboxFixture.js';
import { signalFieldsAt, signalSignedWith } from '../../support/mirrorFixture.js';
import {
  ORACLE_APPROVAL_FLOOR_MINOR_UNITS,
  ORACLE_FULL_HALT_MS,
  expectedFor,
  expectedUnderFullHalt,
  type OracleCase,
  type OracleState,
} from '../../support/mirrorPrecedenceTable.js';
import { enqueueDispatch } from '../../../src/kernel/outbox/enqueue.js';
import { claimForExternalDispatch } from '../../../src/kernel/outbox/claim.js';
import {
  consumeCorroboration,
  declareMirrorDegraded,
  evaluateState,
} from '../../../src/kernel/mirror/mirrorStateMachine.js';
import { signalSigningBytes } from '../../../src/kernel/mirror/corroborationSignal.js';
import { grantOverride, type OverrideRequest } from '../../../src/kernel/mirror/degradedModeOverride.js';
import { overrideGrantBytes } from '../../../src/kernel/mirror/degradedModeOverride.js';
import { sign as signEd25519 } from 'node:crypto';
import { money } from '../../../src/kernel/exposure/money.js';
import { unsafeStaleEligibilityClaim } from '../../negative-controls/unsafe-stale-eligibility.js';

/**
 * `§13`, `§14`, `§15`, `§16`, `§33` — ELIGIBILITY IS DECIDED AT CLAIM TIME, FROM CURRENT
 * AUTHORITATIVE STATE.
 *
 * =================================================================================
 * THE RULE THE CLAIM OBEYS, VERBATIM (`30 §5.1` item 3's ordering block):
 *
 *   COMMIT  →  push to audit store  →  "dispatch, per (4)"
 *
 * Item 4 is the ordered first-match precedence list, and the CLAIM is the first durable
 * step of "dispatch". So item 4 is evaluated HERE, in the claim transaction, over operands
 * read there — not at enqueue, and never from a value a caller stored.
 *
 * `§13`: "An outbox row existing does NOT mean it can still be claimed. Mirror state, owner
 * override, statutory clock state, approval state or another current pre-dispatch operand
 * can change between enqueue and claim."
 *
 * THE OUTBOX TABLE HAS NO ELIGIBILITY COLUMN. `0010` adds none, deliberately, so `§14`'s
 * attack — an implementation trusting `eligible_at_enqueue = true` — has no field to trust.
 * The vulnerable control that carries one is `unsafe-stale-eligibility.ts`, and it is
 * TEST-ONLY.
 * =================================================================================
 *
 * =================================================================================
 * THE EXPECTATIONS COME FROM THE HAND-AUTHORED ORACLE.
 *
 * `mirrorPrecedenceTable.ts` transcribes `22 §3.1` and `30 §5.1` item 4 by hand and imports
 * nothing from `src/`. Every disposition asserted below is `expectedFor` /
 * `expectedUnderFullHalt`'s answer, never `classifyDispatchPrecedence`'s — `36 §0`'s rule
 * about self-validating tests, and `§39` of the S1H mandate in its own words: "Forbidden:
 * expected precedence generated by production rule list."
 *
 * `clockBearing` IS FALSE FOR EVERY CASE, and that is `S1I-C1` rather than a choice.
 * v1.3.3 declares no binding from an effect to a `statutory_clock.case_ref`, so the claim
 * reads the operand in the fail-closed direction and row 3 is unreachable at claim time.
 * `claim.ts`'s `clockBearingAtClaim` carries the full argument and `S1I-result.md §9`
 * reports the leg PARTIAL.
 * =================================================================================
 */

let h: OutboxHarness;
const T0 = new Date('2026-09-05T10:05:00.000Z');
const WORKER = 'worker:s1i-eligibility';

beforeAll(async () => {
  h = await createOutboxHarness();
});

afterAll(async () => {
  await h.close();
});

beforeEach(async () => {
  await h.reset();
});

// =====================================================================================
// MOVING THE MIRROR STATE. Production functions only; nothing is written by hand.
// =====================================================================================

async function toUncorroboratedStall(at: Date): Promise<void> {
  await declareMirrorDegraded(h.control, COMPANY_ID, 'PUSH_ACK_TIMEOUT', at);
  expect((await evaluateState(h.control, COMPANY_ID, at)).state).toBe('UNCORROBORATED_STALL');
}

async function toCorroboratedDegraded(at: Date): Promise<void> {
  await declareMirrorDegraded(h.control, COMPANY_ID, 'PUSH_ACK_TIMEOUT', at);
  const signal = signalSignedWith(
    signalFieldsAt(at, { signalId: `signal:s1i-${String(at.getTime())}` }),
    h.auditKey.privateKey,
    signalSigningBytes,
  );
  const outcome = await consumeCorroboration(
    h.control,
    COMPANY_ID,
    signal,
    h.auditKey.publicKey,
    at,
  );
  expect(outcome.kind).toBe('SIGNAL_CONSUMED');
  expect((await evaluateState(h.control, COMPANY_ID, at)).state).toBe('CORROBORATED_DEGRADED');
}

async function enterState(state: OracleState, at: Date): Promise<void> {
  if (state === 'NORMAL') return;
  if (state === 'UNCORROBORATED_STALL') {
    await toUncorroboratedStall(at);
    return;
  }
  await toCorroboratedDegraded(at);
}

async function enqueue(effect: AuthorisedEffect, tag: string): Promise<void> {
  const outcome = await enqueueDispatch(h.control, {
    companyId: COMPANY_ID,
    effectId: effect.effectId,
    outboxId: `outbox:${tag}`,
    payloadCanonicalBytes: effect.payloadCanonicalBytes,
    now: T0,
  });
  expect(outcome.kind).toBe('ENQUEUED');
}

/** The claim's outcome, reduced to the oracle's own vocabulary. */
async function claimDisposition(
  effect: AuthorisedEffect,
  at: Date,
): Promise<{ readonly disposition: string; readonly row: number | null; readonly tag: boolean | null }> {
  const result = await claimForExternalDispatch(h.control, {
    companyId: COMPANY_ID,
    idempotencyKey: effect.idempotencyKey,
    claimedBy: WORKER,
    now: at,
  });
  if (result.kind === 'CLAIMED') {
    return {
      disposition: 'DISPATCH_ELIGIBLE',
      row: result.claim.matchedRow,
      tag: result.claim.requiresUnmirroredTag,
    };
  }
  const mapped =
    result.reason === 'PRE_DISPATCH_HALTED'
      ? 'HALT'
      : result.reason === 'PRE_DISPATCH_SUSPENDED'
        ? 'SUSPEND'
        : result.reason;
  return {
    disposition: mapped,
    row: result.decision?.matchedRow ?? null,
    tag: result.decision?.requiresUnmirroredTag ?? null,
  };
}

// =====================================================================================
// `§15` — EVERY RECOVERABILITY CLASS, IN EVERY MIRROR STATE
// =====================================================================================

const STATES: readonly OracleState[] = ['NORMAL', 'UNCORROBORATED_STALL', 'CORROBORATED_DEGRADED'];

describe('`§15` — the three recoverability classes, in all three mirror states', () => {
  for (const state of STATES) {
    it(`REVERSIBLE in ${state}: the oracle's row 5, and the tag follows the state`, async () => {
      const effect = await authorisePause(h, { resourceId: `CMP-${state}` });
      await enqueue(effect, `rev-${state}`);
      await enterState(state, T0);

      const oracleCase: OracleCase = {
        recoverability: 'REVERSIBLE',
        clockBearing: false,
        totalExposure: '0.00',
        hasRecordedApproval: false,
      };
      const expectedDisposition = expectedFor(state, oracleCase);
      const actual = await claimDisposition(effect, T0);

      expect(actual.disposition).toBe(expectedDisposition.disposition);
      expect(actual.row).toBe(expectedDisposition.row);
      // `36 §6`: in `CORROBORATED_DEGRADED`, "every dispatch tagged
      // `DISPATCHED_UNMIRRORED`". `§16`: the claim must PRESERVE that requirement.
      expect(actual.tag).toBe(expectedDisposition.requiresUnmirroredTag);

      const rows = await outboxRows(h.control);
      if (expectedDisposition.disposition === 'DISPATCH_ELIGIBLE') {
        expect(rows[0]!.status).toBe('CLAIMED');
        expect(rows[0]!.claimMirrorState).toBe(state);
        expect(rows[0]!.claimRequiresUnmirroredTag).toBe(
          expectedDisposition.requiresUnmirroredTag,
        );
      } else {
        // NOTHING IS WRITTEN on a refusal. `§14`'s reverse case depends on it.
        expect(rows[0]!.status).toBe('ENQUEUED');
        expect(await claimJournalRows(h.control)).toHaveLength(0);
      }
    });

    it(`COMPENSABLE discretionary in ${state}: SUSPEND at row 4, and nothing is written`, async () => {
      const effect = await authoriseRefund(h);
      await enqueue(effect, `comp-${state}`);
      await enterState(state, T0);

      const oracleCase: OracleCase = {
        recoverability: 'COMPENSABLE',
        // `S1I-C1`: v1.3.3 declares no effect→`case_ref` binding, so the claim reads this
        // operand FALSE. Row 3 is therefore unreachable and the effect falls to row 4.
        clockBearing: false,
        totalExposure: '10.00',
        hasRecordedApproval: false,
      };
      const expectedDisposition = expectedFor(state, oracleCase);
      expect(expectedDisposition.disposition).toBe('SUSPEND');

      const actual = await claimDisposition(effect, T0);
      expect(actual.disposition).toBe('SUSPEND');
      expect(actual.row).toBe(expectedDisposition.row);
      expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
      expect(await claimJournalRows(h.control)).toHaveLength(0);
    });

    it(`IRRECOVERABLE in ${state}: row 1, and its behaviour follows the STATE`, async () => {
      /*
       * `30 §5.1` item 4 row 1 as v1.3.4 (IRN-01) issues it: "In `NORMAL`, **dispatch** —
       * subject to every ordinary authority requirement [...] In `UNCORROBORATED_STALL`
       * and in `CORROBORATED_DEGRADED`, **halt** [...] `NORMAL` is the state in which the
       * effect is *not* unmirrored."
       *
       * Until v1.3.4 this case asserted HALT in all three states, which is what
       * `S1I-C6` reported as a finding: `22 §3.1` printed Halt/Halt/Halt, so the class
       * ADR-026 is titled for could never reach a claim at all and ADR-026's own decision
       * items 2 through 5 had no subject. `30 §5.1b` records the correction and its
       * bounds.
       *
       * THE EXPECTATION IS THE HAND-AUTHORED ORACLE'S, NOT PRODUCTION'S. `36 §0`:
       * `expectedFor` is transcribed from `22 §3.1` and `30 §5.1` and imports nothing.
       */
      const effect = await authoriseReship(h, { resourceId: `ORD-RESHIP-${state}` });
      await enqueue(effect, `irr-${state}`);
      await enterState(state, T0);

      const oracleCase: OracleCase = {
        recoverability: 'IRRECOVERABLE',
        clockBearing: false,
        totalExposure: '0.00',
        hasRecordedApproval: false,
      };
      const expectedDisposition = expectedFor(state, oracleCase);
      expect(expectedDisposition.row).toBe(1);
      expect(expectedDisposition.disposition).toBe(
        state === 'NORMAL' ? 'DISPATCH_ELIGIBLE' : 'HALT',
      );

      const actual = await claimDisposition(effect, T0);
      expect(actual.row).toBe(1);
      expect(actual.disposition).toBe(expectedDisposition.disposition);
      // In `NORMAL` the row is durably CLAIMED; in either degraded state nothing is
      // written and the row stays claimable if the state later recovers (`§14`).
      expect((await outboxRows(h.control))[0]!.status).toBe(
        state === 'NORMAL' ? 'CLAIMED' : 'ENQUEUED',
      );
    });
  }
});

describe('`30 §5.1a` — ROW 2, AND THE FLOOR IS STRICT', () => {
  it('`$20.00` is NOT above the floor: the effect falls to row 4 and SUSPENDS', async () => {
    // `51 §3.7`: "the comparison is strict [...] `$20.00` exactly is NOT above the floor".
    // The oracle's own transcribed constant is asserted first, so the boundary this case
    // sits on is the declared one.
    expect(ORACLE_APPROVAL_FLOOR_MINOR_UNITS).toBe(2000n);
    const effect = await authoriseRefundAtExposure(h, '20.00');
    await enqueue(effect, 'at-floor');
    const actual = await claimDisposition(effect, T0);
    expect(actual.disposition).toBe('SUSPEND');
    expect(actual.row).toBe(4);
  });

  it('`$20.01` IS above the floor: row 2 matches and the claim is HALTED', async () => {
    const effect = await authoriseRefundAtExposure(h, '20.01');
    await enqueue(effect, 'above-floor');
    const oracleCase: OracleCase = {
      recoverability: 'COMPENSABLE',
      clockBearing: false,
      totalExposure: '20.01',
      hasRecordedApproval: false,
    };
    expect(expectedFor('NORMAL', oracleCase).row).toBe(2);
    const actual = await claimDisposition(effect, T0);
    expect(actual.disposition).toBe('HALT');
    expect(actual.row).toBe(2);
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });
});

describe('`§15` — THE FULL-HALT POSTURE BLOCKS THE CLAIM', () => {
  it('at `PT30M` every class is halted, REVERSIBLE included', async () => {
    /*
     * `30 §5.1` item 5: "Mirror unreachable continuously for at or beyond
     * `audit_unreachable_full_halt_threshold` (**30 minutes**, `51 §3.8`) halts **all**
     * classes including REVERSIBLE — the point at which the company stops."
     *
     * `30 §5.1a`: "In the posture, item 4's ordered list is evaluated and then every
     * disposition is reduced to Halt."
     */
    expect(ORACLE_FULL_HALT_MS).toBe(1_800_000);
    const effect = await authorisePause(h, { resourceId: 'CMP-FULL-HALT' });
    await enqueue(effect, 'full-halt');
    await toUncorroboratedStall(T0);

    // ONE MINUTE UNDER the threshold: row 5 still dispatches.
    const under = new Date(T0.getTime() + ORACLE_FULL_HALT_MS - 60_000);
    const beforePosture = await claimDisposition(effect, under);
    expect(beforePosture.disposition).toBe('DISPATCH_ELIGIBLE');
  });

  it('AT the threshold, to the microsecond, a REVERSIBLE claim is refused', async () => {
    const effect = await authorisePause(h, { resourceId: 'CMP-FULL-HALT-AT' });
    await enqueue(effect, 'full-halt-at');
    await toUncorroboratedStall(T0);

    const oracleCase: OracleCase = {
      recoverability: 'REVERSIBLE',
      clockBearing: false,
      totalExposure: '0.00',
      hasRecordedApproval: false,
    };
    const expectation = expectedUnderFullHalt('UNCORROBORATED_STALL', oracleCase, false);
    expect(expectation.disposition).toBe('HALT');

    const at = new Date(T0.getTime() + ORACLE_FULL_HALT_MS);
    const actual = await claimDisposition(effect, at);
    expect(actual.disposition).toBe('HALT');
    // `30 §5.1a`: "Row 5's REVERSIBLE dispatch, which the posture is what halts, has NO
    // override path — `precedence_rows` cannot hold 5."
    expect(actual.row).toBe(5);
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });

  it('and in CORROBORATED_DEGRADED too — corroboration proves the stall, it does not cure it', async () => {
    // `30 §5.1a`: "It applies in BOTH degraded states, including `CORROBORATED_DEGRADED`:
    // item 5 qualifies the halt by no state, and corroboration PROVES the stall rather
    // than curing it."
    const effect = await authorisePause(h, { resourceId: 'CMP-FULL-HALT-CORR' });
    await enqueue(effect, 'full-halt-corr');
    await toCorroboratedDegraded(T0);
    const at = new Date(T0.getTime() + ORACLE_FULL_HALT_MS + 1);
    const actual = await claimDisposition(effect, at);
    expect(actual.disposition).toBe('HALT');
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });
});

describe('`§14` — STALE ELIGIBILITY, AND THE REVERSE CASE', () => {
  it('eligible at enqueue, HALTED at claim: production re-evaluates and refuses', async () => {
    /*
     * `§14`'s required attack, step by step:
     *
     *   1. the effect is eligible while the mirror state is NORMAL;
     *   2. the outbox waits;
     *   3. control enters a state where the effect must HALT;
     *   4. a claim is attempted.
     *
     * Production reads the CURRENT state and refuses. `unsafeStaleEligibilityClaim` reads
     * the value recorded at enqueue and claims.
     */
    const effect = await authorisePause(h, { resourceId: 'CMP-STALE' });
    await enqueue(effect, 'stale');

    // 1. Eligible NOW, under NORMAL. Asserted rather than assumed — this is what makes the
    //    later refusal a CHANGE rather than a class that was never eligible.
    expect((await evaluateState(h.control, COMPANY_ID, T0)).state).toBe('NORMAL');

    // 3. The state changes to one in which row 5 halts: the FULL-HALT POSTURE.
    await toUncorroboratedStall(T0);
    const at = new Date(T0.getTime() + ORACLE_FULL_HALT_MS + 1000);

    // 4. Production refuses.
    const actual = await claimDisposition(effect, at);
    expect(actual.disposition).toBe('HALT');
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');

    // THE DISCRIMINATION. The unsafe path trusts `eligible_at_enqueue` and claims.
    const unsafe = await unsafeStaleEligibilityClaim(h.control, {
      companyId: COMPANY_ID,
      idempotencyKey: effect.idempotencyKey,
      // Recorded when the row was enqueued, under NORMAL. This is the field production
      // does not have.
      eligibleAtEnqueue: true,
      claimedBy: 'unsafe:stale',
      now: at,
    });
    expect(unsafe).toBe('CLAIMED');
    // AND THE PRODUCTION ROW IS STILL ENQUEUED: the control writes only to its own ledger.
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });

  it('SUSPENDED at enqueue, eligible later: the claim succeeds when the state recovers', async () => {
    /*
     * `§14`'s reverse case, verbatim: "outbox initially suspended; state later legitimately
     * becomes eligible; claim may succeed if every current prerequisite is satisfied. Do
     * not make the outbox permanently inherit an old degraded-state classification."
     */
    const effect = await authorisePause(h, { resourceId: 'CMP-RECOVER' });
    await enqueue(effect, 'recover');
    await toUncorroboratedStall(T0);

    // In the posture, HALTED.
    const inPosture = new Date(T0.getTime() + ORACLE_FULL_HALT_MS + 1);
    expect((await claimDisposition(effect, inPosture)).disposition).toBe('HALT');
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');

    // The declaration closes, so `NORMAL` is derived again and the posture is gone.
    const { closeMirrorDeclaration } = await import(
      '../../../src/kernel/mirror/mirrorStateMachine.js'
    );
    const recoveredAt = new Date(inPosture.getTime() + 60_000);
    await closeMirrorDeclaration(h.control, COMPANY_ID, recoveredAt);
    expect((await evaluateState(h.control, COMPANY_ID, recoveredAt)).state).toBe('NORMAL');

    // THE SAME ROW, now claimable. It inherited nothing.
    const after = await claimDisposition(effect, recoveredAt);
    expect(after.disposition).toBe('DISPATCH_ELIGIBLE');
    expect(after.row).toBe(5);
    expect(after.tag).toBe(false);
    const rows = await outboxRows(h.control);
    expect(rows[0]!.status).toBe('CLAIMED');
    expect(rows[0]!.claimMirrorState).toBe('NORMAL');
  });
});

describe('`§33` — THE MIRROR STATE IS READ AT CLAIM TIME, ACROSS A RESTART', () => {
  it('enqueued under NORMAL, restarted, now degraded: the claim follows CURRENT state', async () => {
    const effect = await authorisePause(h, { resourceId: 'CMP-RESTART-DEGRADED' });
    await enqueue(effect, 'restart-degraded');
    expect((await evaluateState(h.control, COMPANY_ID, T0)).state).toBe('NORMAL');

    await toUncorroboratedStall(T0);

    // The restart: a brand-new pool, no in-memory state carried across.
    const { createPool } = await import('../../../src/db/pool.js');
    const revived = createPool({
      connectionString: h.replication.control.url,
      applicationName: 'acos-s1i-restart-degraded',
    });
    try {
      const at = new Date(T0.getTime() + 60_000);
      const result = await claimForExternalDispatch(revived, {
        companyId: COMPANY_ID,
        idempotencyKey: effect.idempotencyKey,
        claimedBy: 'worker:restarted',
        now: at,
      });
      // `UNCORROBORATED_STALL`, under the threshold: row 5 still dispatches (`22 §3.1`),
      // and the recorded state is the CURRENT one rather than the enqueue-time one.
      expect(result.kind).toBe('CLAIMED');
      if (result.kind === 'CLAIMED') {
        expect(result.claim.mirrorState).toBe('UNCORROBORATED_STALL');
        // `I17f(a)`: not tagged in `UNCORROBORATED_STALL`, because no covering PUBLISHED
        // interval is known to exist. `36 §6` tags only `CORROBORATED_DEGRADED`.
        expect(result.claim.requiresUnmirroredTag).toBe(false);
      }
    } finally {
      await revived.end();
    }
  });

  it('enqueued under a degraded state, recovered to NORMAL: the claim follows NORMAL', async () => {
    await toUncorroboratedStall(T0);
    const effect = await authorisePause(h, { resourceId: 'CMP-ENQ-DEGRADED' });
    await enqueue(effect, 'enq-degraded');

    const { closeMirrorDeclaration } = await import(
      '../../../src/kernel/mirror/mirrorStateMachine.js'
    );
    const recoveredAt = new Date(T0.getTime() + 5 * 60_000);
    await closeMirrorDeclaration(h.control, COMPANY_ID, recoveredAt);

    const result = await claimForExternalDispatch(h.control, {
      companyId: COMPANY_ID,
      idempotencyKey: effect.idempotencyKey,
      claimedBy: WORKER,
      now: recoveredAt,
    });
    expect(result.kind).toBe('CLAIMED');
    if (result.kind === 'CLAIMED') {
      expect(result.claim.mirrorState).toBe('NORMAL');
      expect(result.claim.requiresUnmirroredTag).toBe(false);
    }
  });
});

describe('`§16` — THE `DISPATCHED_UNMIRRORED` REQUIREMENT IS PRESERVED IMMUTABLY', () => {
  it('a claim in CORROBORATED_DEGRADED records the requirement on the row AND the journal', async () => {
    const effect = await authorisePause(h, { resourceId: 'CMP-TAGGED' });
    await enqueue(effect, 'tagged');
    await toCorroboratedDegraded(T0);

    const result = await claimForExternalDispatch(h.control, {
      companyId: COMPANY_ID,
      idempotencyKey: effect.idempotencyKey,
      claimedBy: WORKER,
      now: T0,
    });
    expect(result.kind).toBe('CLAIMED');
    if (result.kind !== 'CLAIMED') return;
    // `36 §6`: "`CORROBORATED_DEGRADED`: as `NORMAL`, with EVERY DISPATCH TAGGED".
    expect(result.claim.requiresUnmirroredTag).toBe(true);

    const rows = await outboxRows(h.control);
    expect(rows[0]!.claimRequiresUnmirroredTag).toBe(true);
    expect(rows[0]!.claimMirrorState).toBe('CORROBORATED_DEGRADED');

    const journal = await claimJournalRows(h.control);
    expect(journal[0]!.requiresUnmirroredTag).toBe(true);
    expect(journal[0]!.mirrorState).toBe('CORROBORATED_DEGRADED');

    /*
     * IMMUTABLE. `§16`: "The future adapter/execution slice must not be able to 'forget'
     * that the dispatch occurred outside NORMAL."
     *
     * `dispatch_outbox_state_machine` refuses every UPDATE to a `CLAIMED` row, so there is
     * no statement that clears the flag. And the journal row is chained, so
     * `effect_journal_immutable_except_mirrored_at` refuses it there too.
     */
    const client = await h.control.connect();
    try {
      await expect(
        client.query(
          `UPDATE dispatch_outbox SET claim_requires_unmirrored_tag = FALSE
            WHERE company_id = $1 AND idempotency_key = $2`,
          [COMPANY_ID, effect.idempotencyKey],
        ),
      ).rejects.toThrow(/OUTBOX_ROW_ALREADY_CLAIMED/);
      await expect(
        client.query(
          `UPDATE effect_journal SET outbox_requires_unmirrored_tag = FALSE
            WHERE company_id = $1 AND journal_row_kind = 'OUTBOX_CLAIMED'`,
          [COMPANY_ID],
        ),
      ).rejects.toThrow(/JOURNAL_ROW_IMMUTABLE/);
    } finally {
      client.release();
    }

    // AND IT IS NOT A TAG ON A DISPATCHED EFFECT. `§16`: "Do NOT mark the effect itself
    // DISPATCHED. Do NOT claim I17f(a)/(c) closed yet."
    const statuses = await h.control.query<{ status: string }>(
      `SELECT status FROM effect WHERE company_id = $1`,
      [COMPANY_ID],
    );
    for (const row of statuses.rows) expect(row.status).toBe('AUTHORISED');
  });
});

describe('`§31` — AN OVERRIDE-BACKED CLAIM BINDS THE SPECIFIC AUTHORITY', () => {
  const HOUR = 60 * 60 * 1000;

  async function grantRow4Override(overrideId: string, cap: bigint): Promise<void> {
    const request: OverrideRequest = {
      companyId: COMPANY_ID,
      overrideId,
      requestedBy: 'principal:owner',
      requestedAt: T0,
      effectClasses: ['refund.create'],
      // `30 §5.7.2`: `recoverability_classes[] ⊆ {COMPENSABLE, REVERSIBLE}`.
      recoverabilityClasses: ['COMPENSABLE'],
      // `30 §5.1` item 5: "An override restores precedence rows 3 and 4 only".
      precedenceRows: [4],
      startsAt: T0,
      expiresAt: new Date(T0.getTime() + 24 * HOUR),
      effectCountCap: cap,
      monetaryExposureCap: money('50.00'),
      reason: 'the S1I override-backed claim (§31)',
      incidentRef: h.seed.incidentRef,
    };
    await grantOverride(h.control, request, {
      grantedBy: 'principal:owner',
      grantedAt: T0,
      grantSignature: signEd25519(
        null,
        overrideGrantBytes(request),
        h.seed.ownerSigner.privateKey,
      ),
    });
  }

  it('a row-4 COMPENSABLE claim succeeds under an in-scope override, tagged and bound', async () => {
    const effect = await authoriseRefund(h);
    await enqueue(effect, 'override-claim');
    await toUncorroboratedStall(T0);
    await grantRow4Override('override:s1i-row4', 5n);

    const result = await claimForExternalDispatch(h.control, {
      companyId: COMPANY_ID,
      idempotencyKey: effect.idempotencyKey,
      claimedBy: WORKER,
      now: T0,
    });
    expect(result.kind).toBe('CLAIMED');
    if (result.kind !== 'CLAIMED') return;
    expect(result.claim.matchedRow).toBe(4);
    // `30 §5.7.2` item 5: "Every dispatch under it is tagged `DISPATCHED_UNMIRRORED` AND
    // CARRIES `override_id`."
    expect(result.claim.requiresUnmirroredTag).toBe(true);
    expect(result.claim.overrideId).toBe('override:s1i-row4');

    const rows = await outboxRows(h.control);
    // `§31`: "Do not merely persist `overrideApplied = true`. Bind the exact authoritative
    // override identity."
    expect(rows[0]!.claimOverrideId).toBe('override:s1i-row4');
    expect(rows[0]!.claimRequiresUnmirroredTag).toBe(true);

    const journal = await claimJournalRows(h.control);
    expect(journal[0]!.overrideId).toBe('override:s1i-row4');

    // `30 §5.7.2` item 3: the counters are incremented in the dispatching transaction.
    const counters = await h.control.query<{
      effects_dispatched: string;
      monetary_dispatched: string;
    }>(
      `SELECT effects_dispatched, monetary_dispatched FROM degraded_mode_override
        WHERE company_id = $1 AND override_id = 'override:s1i-row4'`,
      [COMPANY_ID],
    );
    expect(counters.rows[0]!.effects_dispatched).toBe('1');
    expect(counters.rows[0]!.monetary_dispatched).toBe('10.00');
  });

  it('an EXPIRED override does not admit the claim', async () => {
    const effect = await authoriseRefund(h);
    await enqueue(effect, 'override-expired');
    await toUncorroboratedStall(T0);
    await grantRow4Override('override:s1i-expiring', 5n);

    // `30 §5.7.2` item 2: `[starts_at, expires_at)` is half-open. One millisecond past the
    // 24-hour box, the override covers nothing.
    const past = new Date(T0.getTime() + 24 * HOUR + 1);
    const actual = await claimDisposition(effect, past);
    expect(actual.disposition).toBe('HALT');
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });

  it('an override scoped to another action class does not admit the claim', async () => {
    const effect = await authoriseRefund(h);
    await enqueue(effect, 'override-scope');
    await toUncorroboratedStall(T0);

    const request: OverrideRequest = {
      companyId: COMPANY_ID,
      overrideId: 'override:s1i-other-class',
      requestedBy: 'principal:owner',
      requestedAt: T0,
      // `I63(a)`: "no effect is dispatched under a `DegradedModeOverride` outside its
      // declared `effect_classes[]`".
      effectClasses: ['campaign.budget.set'],
      recoverabilityClasses: ['COMPENSABLE'],
      precedenceRows: [4],
      startsAt: T0,
      expiresAt: new Date(T0.getTime() + 24 * HOUR),
      effectCountCap: 5n,
      monetaryExposureCap: money('50.00'),
      reason: 'an out-of-scope override (§31)',
      incidentRef: h.seed.incidentRef,
    };
    await grantOverride(h.control, request, {
      grantedBy: 'principal:owner',
      grantedAt: T0,
      grantSignature: signEd25519(
        null,
        overrideGrantBytes(request),
        h.seed.ownerSigner.privateKey,
      ),
    });

    const actual = await claimDisposition(effect, T0);
    expect(actual.disposition).toBe('SUSPEND');
    expect((await outboxRows(h.control))[0]!.status).toBe('ENQUEUED');
  });

  it('and an override can NEVER admit an IRRECOVERABLE effect', async () => {
    /*
     * `30 §5.7.2`'s scope rule: "`recoverability_classes[]` therefore excludes
     * `IRRECOVERABLE` STRUCTURALLY at MVP, not by policy: there is no grant path that
     * admits it." `51 §3.6` makes `{3, 4}` the structural grantable set.
     *
     * So the attack cannot even be constructed: the grant is refused by the database
     * before any claim is attempted.
     */
    const effect = await authoriseReship(h, { resourceId: 'ORD-RESHIP-OVERRIDE' });
    await enqueue(effect, 'override-irrecoverable');
    await toUncorroboratedStall(T0);

    const client = await h.control.connect();
    try {
      await expect(
        client.query(
          `INSERT INTO degraded_mode_override
             (company_id, override_id, requested_by, requested_at, effect_classes,
              recoverability_classes, precedence_rows, starts_at, expires_at,
              effect_count_cap, effects_dispatched, monetary_exposure_cap,
              monetary_dispatched, reason, incident_ref, status)
           VALUES ($1, 'override:irrecoverable', 'principal:owner', $2,
                   ARRAY['fulfilment.reship'], ARRAY['IRRECOVERABLE'], ARRAY[1],
                   $2, $3, 5, 0, 50.00, 0.00, 'the impossible grant', $4, 'ACTIVE')`,
          [COMPANY_ID, T0, new Date(T0.getTime() + 24 * HOUR), h.seed.incidentRef.toString()],
        ),
      ).rejects.toThrow();
    } finally {
      client.release();
    }

    // And with no override, the claim halts at row 1 as it always does.
    const actual = await claimDisposition(effect, T0);
    expect(actual.disposition).toBe('HALT');
    expect(actual.row).toBe(1);
  });
});
