import { randomUUID, sign as signEd25519, type KeyObject } from 'node:crypto';

import { inTransaction, type Client, type Pool } from '../db/pool.js';
import { evaluateTransportCompleteness } from './transportCompleteness.js';

/**
 * `30 §5.7.1` — THE AUDIT PLANE'S OWN OBSERVATION, PUBLISHED INTERVAL AND SIGNED SIGNAL.
 *
 * =================================================================================
 * THE SIGNAL IS GENERATED FROM AUDIT-OWNED FACTS AND FROM NOTHING ELSE.
 *
 * `24 §3` K11's declared inputs are "the control plane's primary journal rows [...]
 * `JournalAttestation` rows every 5 minutes; its own read-only vendor credentials;
 * independently computed metrics." `30 §5.4`: the audit plane "has no independent reading
 * of [the true control maximum] and BY CONSTRUCTION CANNOT: R10 removed the replica
 * deliberately."
 *
 * So this module reads:
 *
 *   - `audit_journal`, through `evaluateTransportCompleteness` — rows this store received
 *     and independently re-chained, and the ATTESTATION ABSENCE that `30 §5.7` says cannot
 *     be forged: "Absence of expected attestations (k=3) | audit-internal observation |
 *     **No.** It is an absence observed by the other party."
 *   - its own store's reachability, by probing it — `30 §5.7`: "Its own reachability probe
 *     of its own store | audit-internal observation | **No** [not forgeable]."
 *
 * AND IT READS NONE OF THESE, none of which has an argument position anywhere in the file:
 *
 *   - the control plane's `mirrored_at`        (not a column of this store)
 *   - the control plane's declared mirror state (arrives only as a journal row, and is
 *                                                `I17f(b)`'s SUBJECT, not an input)
 *   - a caller-supplied audit-health boolean    (there is no such parameter)
 *   - a model claim of any kind
 *   - the control database                      (`plane-independence.test.ts` asserts that
 *                                                no file under `src/audit/` names
 *                                                `controlUrl` or a control repository)
 * =================================================================================
 *
 * =================================================================================
 * THE PRIVATE KEY. `30 §5.7.1`, Signer: "The audit plane, under an Ed25519 key **generated
 * on and never leaving the audit-plane host**. The control plane holds **only the public
 * key**, distributed as control artifact class 24 (`50 §2`) and hashed into the owner-signed
 * manifest, so a substituted public key is an `I19` mismatch."
 *
 * The signing key is a PARAMETER of `issueSignal`, and it is a private `KeyObject`. Two
 * consequences, both intended:
 *
 *   1. NO KEY MANAGEMENT IS BUILT. `§5.7.1`'s Provisioning note puts it outside S1: "The
 *      signing key and the read endpoint are part of audit separation, not part of the S1
 *      build, and `62 §7` authorises provisioning them now." At S1H the key is generated by
 *      the harness. `S1H-result.md §5` reports provisioning OPEN, and `I19`'s runtime
 *      verification of class 24 stays OPEN with the rest of the class-20 residual.
 *
 *   2. NOTHING IN `src/kernel/` CAN SIGN ONE. The signer lives in `src/audit/`, the verifier
 *      in `src/kernel/mirror/corroborationSignal.ts`, and `audit-signal-ownership.test.ts`
 *      asserts as a source property that no file outside `src/audit/` produces a signal
 *      signature. A control plane that could mint its own corroboration is `52 §1` Path B.
 * =================================================================================
 */

/** `30 §5.7.1`'s `reason` enum, transcribed on the audit side. */
export type StallReason = 'ATTESTATION_STALL' | 'PUSH_PATH_UNREACHABLE' | 'STORE_WRITE_REJECTED';

/**
 * The audit plane's own reading of the stall condition.
 *
 * `null` when no stall condition holds, which is `30 §5.7.1`'s Issuance rule: "**No signal
 * is issued when no stall condition holds.**"
 */
export interface StallObservation {
  readonly companyId: string;
  readonly reason: StallReason;
  readonly observedAt: Date;
  /** `30 §5.7.1`'s `last_attestation_seq` — "the newest `max_journal_seq` the audit plane received". */
  readonly lastAttestationSeq: bigint;
  readonly lastAttestationReceivedAt: Date | null;
  readonly detail: string;
}

/**
 * Observe whether a stall condition holds, from audit-owned facts.
 *
 * =================================================================================
 * WHICH REASONS THIS DERIVES, AND WHICH ONE IT REFUSES TO DERIVE.
 *
 * `ATTESTATION_STALL` — derived. `evaluateTransportCompleteness` produces the finding from
 * `audit_journal` alone at `k × cadence` = 15 minutes (`30 §5.4`), and that is the absence
 * `§5.7` says is unforgeable.
 *
 * `PUSH_PATH_UNREACHABLE` — derived from THIS STORE'S OWN reachability probe, which is
 * `§5.7`'s second unforgeable audit-internal observation. The probe is a real query against
 * the audit store; if the store cannot answer, the audit plane cannot publish anything
 * either, which is `§5.6`'s "Audit store down | No — its own checks cannot run | No".
 *
 * `STORE_WRITE_REJECTED` — **DERIVED, under v1.3.3's `30 §5.7.1a`, from the audit plane's
 * own `audit_store_write_failure` observations and from nothing else.**
 *
 * v1.3.2 declared the enum member and no derivation, and the one reading a reader reaches
 * for — insert-quota saturation — is EXPLICITLY FORBIDDEN as a mode transition:
 *
 *   `30 §5.1` item 5: "Audit-store saturation is an incident, not a mode change (I17c)."
 *   `30 §5.6`'s reachability table: "Audit insert quota saturated (`I17c`) | Yes | Yes | Yes
 *   | **Yes**, but `§5.1` item 5 declares saturation *an incident, not a mode change*."
 *
 * `§5.7.1a` keeps both statements and gives the member a CLOSED TEN-CONDITION predicate that
 * quota saturation fails at conjunct 8. The predicate is established by `A0001`/`A0004`'s
 * ingest control flow — six of the eight disqualifying conditions leave that function
 * through a `RETURN` rather than an exception, and the trigger performing the canonical,
 * hash and quota checks is `BEFORE INSERT` — so a row in `audit_store_write_failure` is by
 * construction an otherwise-valid, authenticated, in-quota attempt that failed at the store
 * write. THIS FUNCTION READS THAT TABLE AND DERIVES NOTHING ELSE FROM ANYTHING ELSE.
 *
 * `vc-a2d-signal-authenticity.test.ts` still asserts that a saturated quota produces the
 * `AUDIT_QUOTA_SATURATED` incident and NO signal, and
 * `store-write-availability.test.ts` adds the four negative controls and the mandatory
 * positive one.
 *
 * ---------------------------------------------------------------------------------
 * WHICH REASON WINS WHEN BOTH CONDITIONS HOLD, AND WHY THE CHOICE CARRIES NO AUTHORITY.
 *
 * A store-write failure that persists also stops attestations reaching the store, so after
 * `k × cadence` both conditions hold. v1.3.3 declares no precedence between `reason` values
 * and none is needed, because **`reason` is not an authority operand**: `resolveMirrorState`
 * never reads it, `corroborationSignal.ts` checks only that it is a member of the closed
 * enum, and `§5.7.1a` says a `STORE_WRITE_REJECTED` signal "confers exactly what
 * `ATTESTATION_STALL` confers and nothing more". `store-write-availability.test.ts` asserts
 * that both reasons resolve the same state from the same operands.
 *
 * So the choice is diagnostic and this function reports the MORE SPECIFIC observation: the
 * store-write failure is a mechanism the audit plane observed directly, where the
 * attestation stall is an inference from an absence. Recorded as `S1H-C8`'s implementation
 * detail rather than as a reading of a rule the architecture does not state.
 * ---------------------------------------------------------------------------------
 * =================================================================================
 */
export async function observeStall(
  audit: Pool,
  companyId: string,
  now: Date,
): Promise<StallObservation | null> {
  // The reachability probe. `30 §5.7`: "Its own reachability probe of its own store."
  //
  // A store that cannot answer cannot publish, so this returns `null` rather than a
  // `PUSH_PATH_UNREACHABLE` observation it could not record — `30 §5.6`: "Audit store down |
  // No — its own checks cannot run | No | — | **No**". The fail-closed direction.
  try {
    const probe = await audit.connect();
    try {
      await probe.query('SELECT 1');
    } finally {
      probe.release();
    }
  } catch {
    return null;
  }

  const report = await evaluateTransportCompleteness(audit, companyId, now);
  const stall = report.findings.find((f) => f.kind === 'ATTESTATION_STALL');

  // `30 §5.7.1a`. The window is `attestation_cadence × k` = 15 minutes, read from the AUDIT
  // STORE'S OWN transcription (`audit_store_write_failure_window()`) rather than from a
  // constant in this file, for the same reason `issueSignal` reads `max_age` from the store:
  // the value belongs to the instance that owns the artifact.
  const storeWrite = await audit.query<{ observed_at: Date; sqlstate: string }>(
    `SELECT observed_at, sqlstate
       FROM audit_store_write_failure
      WHERE company_id = $1
        AND failure_class = 'AUDIT_STORE_WRITE_UNAVAILABLE'
        AND observed_at > $2::TIMESTAMPTZ - audit_store_write_failure_window()
      ORDER BY observed_at DESC
      LIMIT 1`,
    [companyId, now],
  );
  const failure = storeWrite.rows[0];

  if (failure !== undefined) {
    return {
      companyId,
      reason: 'STORE_WRITE_REJECTED',
      observedAt: now,
      lastAttestationSeq: report.latestAttestation?.attestedMaxJournalSeq ?? 0n,
      lastAttestationReceivedAt: report.latestAttestation?.attestedAt ?? null,
      detail:
        'an otherwise-valid, authenticated, in-quota replication attempt reached audit ' +
        'ingress and could not be made durable: AUDIT_STORE_WRITE_UNAVAILABLE, SQLSTATE ' +
        `${failure.sqlstate} (30 §5.7.1a)`,
    };
  }

  if (stall === undefined) return null;

  return {
    companyId,
    reason: 'ATTESTATION_STALL',
    observedAt: now,
    lastAttestationSeq: report.latestAttestation?.attestedMaxJournalSeq ?? 0n,
    lastAttestationReceivedAt: report.latestAttestation?.attestedAt ?? null,
    detail:
      'k = 3 consecutively missed attestations; undetected silence bounded at 15 minutes ' +
      '(30 §5.4)',
  };
}

export interface PublishedInterval {
  readonly intervalId: string;
  readonly companyId: string;
  readonly intervalStart: Date;
  readonly reason: StallReason;
}

/**
 * Open — or return — the published stall interval for a company.
 *
 * `30 §5.7.1`, replay protection: "`I17f(a)` evaluates every `DISPATCHED_UNMIRRORED`
 * dispatch timestamp against **the audit plane's own record of the intervals it published**,
 * so a dispatch justified by a replayed signal is a critical incident on a fact the control
 * plane does not hold and cannot rewrite."
 *
 * `audit_mirror_stall_interval_one_open` makes a second concurrent interval impossible, and
 * an already-open interval is returned rather than duplicated: a stall that persists is one
 * interval with many issuances, not many intervals.
 */
export async function publishStallInterval(
  audit: Pool,
  observation: StallObservation,
): Promise<PublishedInterval> {
  const client = await audit.connect();
  try {
    return await inTransaction(client, 'READ COMMITTED', async (tx) => {
      const open = await tx.query<{
        interval_id: string;
        interval_start: Date;
        reason: string;
      }>(
        `SELECT interval_id, interval_start, reason FROM audit_mirror_stall_interval
          WHERE company_id = $1 AND interval_end IS NULL`,
        [observation.companyId],
      );
      const existing = open.rows[0];
      if (existing !== undefined) {
        return {
          intervalId: existing.interval_id,
          companyId: observation.companyId,
          intervalStart: existing.interval_start,
          reason: existing.reason as StallReason,
        };
      }

      const intervalId = randomUUID();
      await tx.query(
        `INSERT INTO audit_mirror_stall_interval
           (company_id, interval_id, interval_start, reason,
            opening_last_attestation_seq, opening_last_attestation_received_at, observed_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [
          observation.companyId,
          intervalId,
          observation.observedAt,
          observation.reason,
          observation.lastAttestationSeq.toString(),
          observation.lastAttestationReceivedAt,
          observation.observedAt,
        ],
      );
      return {
        intervalId,
        companyId: observation.companyId,
        intervalStart: observation.observedAt,
        reason: observation.reason,
      };
    });
  } finally {
    client.release();
  }
}

/** Close the open interval. `interval_end` is the only column the trigger permits to move. */
export async function closeStallInterval(
  audit: Pool,
  companyId: string,
  at: Date,
): Promise<boolean> {
  const client = await audit.connect();
  try {
    const result = await client.query(
      `UPDATE audit_mirror_stall_interval SET interval_end = $2
        WHERE company_id = $1 AND interval_end IS NULL`,
      [companyId, at],
    );
    return (result.rowCount ?? 0) > 0;
  } finally {
    client.release();
  }
}

export interface IssuedSignal {
  readonly signalId: string;
  readonly intervalId: string;
  readonly observedAt: Date;
  readonly expiresAt: Date;
}

/**
 * Issue one signed `MirrorInputStallSignal` against an open interval.
 *
 * =================================================================================
 * THE BYTES ARE THE AUDIT DATABASE'S, AND THE SIGNATURE IS THE HOST'S.
 *
 * `30 §5.7.1`: "`signature` bytea — Ed25519 over `ACOS-JCS-1` canonical bytes of the fields
 * above."
 *
 * `audit_mirror_signal_canonical_bytes` on the audit server constructs them — an independent
 * transcription of the declared field order, using `audit_jcs1_*`, on the instance that owns
 * the artifact. This process signs THOSE BYTES and stores them alongside the signature, and
 * `A0002`'s trigger refuses the row unless the store's own recomputation from the structured
 * fields equals what was signed.
 *
 * So three things are simultaneously true of a stored row: the signature covers the audit
 * store's `ACOS-JCS-1` bytes; those bytes are the store's own canonicalisation of the
 * structured columns; and the control plane, which builds the bytes a fourth time from the
 * fields it fetched, verifies against its own construction and never against `signed_bytes`.
 * A canonicaliser divergence is therefore a verification failure rather than a silent
 * disagreement.
 * =================================================================================
 *
 * `30 §5.7.1`, Issuance: "Issued when the audit plane's own checks establish a stall
 * condition, and **re-issued every `attestation_cadence` (5 minutes) for as long as the
 * condition holds, each issuance carrying a fresh `signal_id` and `observed_at`**." Each
 * call is one issuance with a fresh `signal_id`; the caller drives the cadence.
 */
export async function issueSignal(
  audit: Pool,
  interval: PublishedInterval,
  observation: StallObservation,
  auditInstanceId: string,
  signingKey: KeyObject,
): Promise<IssuedSignal> {
  const signalId = randomUUID();
  const client = await audit.connect();
  try {
    return await inTransaction(client, 'READ COMMITTED', async (tx) => {
      // `expires_at = observed_at + max_age`, with `max_age` read from the audit store's own
      // transcription of `30 §5.7.1` rather than from a constant in this file. The CHECK on
      // the table binds the two, so a disagreement is a refused insert.
      const expiry = await tx.query<{ expires_at: Date }>(
        'SELECT ($1::TIMESTAMPTZ + audit_mirror_signal_max_age()) AS expires_at',
        [observation.observedAt],
      );
      const expiresAt = expiry.rows[0]!.expires_at;

      const bytesRow = await tx.query<{ audit_mirror_signal_canonical_bytes: Buffer }>(
        `SELECT audit_mirror_signal_canonical_bytes($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
        [
          signalId,
          interval.companyId,
          observation.observedAt,
          interval.intervalStart,
          observation.lastAttestationSeq.toString(),
          observation.lastAttestationReceivedAt,
          observation.reason,
          expiresAt,
          auditInstanceId,
        ],
      );
      const signedBytes = bytesRow.rows[0]!.audit_mirror_signal_canonical_bytes;

      // The one line in the repository that produces a corroboration signature, and it is
      // inside `src/audit/`.
      const signature = signEd25519(null, signedBytes, signingKey);

      await tx.query(
        `INSERT INTO audit_mirror_input_stall_signal
           (company_id, signal_id, interval_id, observed_at, interval_start,
            last_attestation_seq, last_attestation_received_at, reason, expires_at,
            audit_instance_id, signature, signed_bytes)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
        [
          interval.companyId,
          signalId,
          interval.intervalId,
          observation.observedAt,
          interval.intervalStart,
          observation.lastAttestationSeq.toString(),
          observation.lastAttestationReceivedAt,
          observation.reason,
          expiresAt,
          auditInstanceId,
          signature,
          signedBytes,
        ],
      );

      return { signalId, intervalId: interval.intervalId, observedAt: observation.observedAt, expiresAt };
    });
  } finally {
    client.release();
  }
}

/**
 * The whole audit-side cycle: observe, publish, issue. Returns `null` when no stall holds.
 *
 * `30 §5.7.1`, Issuance: "No signal is issued when no stall condition holds." That is this
 * function's early return, and `vc-a2d-signal-authenticity.test.ts` asserts it by running
 * the cycle against a healthy attestation channel and finding zero signals.
 */
export async function runStallObservationCycle(
  audit: Pool,
  companyId: string,
  now: Date,
  auditInstanceId: string,
  signingKey: KeyObject,
): Promise<IssuedSignal | null> {
  const observation = await observeStall(audit, companyId, now);
  if (observation === null) {
    // The condition has cleared: close any open interval, so `I17f(a)`'s record of what was
    // published has an end. It is NOT reopened by a later stall — that is a new interval.
    await closeStallInterval(audit, companyId, now);
    return null;
  }
  const interval = await publishStallInterval(audit, observation);
  return await issueSignal(audit, interval, observation, auditInstanceId, signingKey);
}

/** The published intervals, for `I17f`'s evaluation and for the tests. */
export async function publishedIntervalsOn(
  client: Client,
  companyId: string,
): Promise<readonly { intervalId: string; start: Date; end: Date | null; reason: string }[]> {
  const result = await client.query<{
    interval_id: string;
    interval_start: Date;
    interval_end: Date | null;
    reason: string;
  }>(
    `SELECT interval_id, interval_start, interval_end, reason
       FROM audit_mirror_stall_interval
      WHERE company_id = $1 ORDER BY interval_start`,
    [companyId],
  );
  return result.rows.map((r) => ({
    intervalId: r.interval_id,
    start: r.interval_start,
    end: r.interval_end,
    reason: r.reason,
  }));
}
