import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import { emitAttestation, ATTESTATION_CADENCE_MS, ATTESTATION_K } from '../../../src/replication/attestation.js';
import {
  ATTESTATION_STALL_BOUND_MS,
  evaluateTransportCompleteness,
} from '../../../src/audit/transportCompleteness.js';
import { CAN03, loadCommerceFixture } from '../../support/enumerationFixture.js';
import {
  S1E_PASS_ORDER,
  loadAuthorityWorld,
  loadS1eOrders,
  s1eSpec,
} from '../../support/authorityFixture.js';
import {
  COMPANY_ID,
  makeLocalAuthorityHarness,
  proposeAndAuthorise,
  type LocalAuthorityHarness,
} from '../../support/localAuthorisationFixture.js';
import {
  createReplicationFixture,
  transportRecordFor,
  type ReplicationFixture,
} from '../../support/replicationFixture.js';

/**
 * STRUCTURAL INDEPENDENCE OF THE TWO PLANES. S1G, `§20`.
 *
 * =================================================================================
 * `30 §5.4`, the sentence that makes this a STRUCTURAL property and not a convention:
 *
 *   "The audit plane has no independent reading of [the control journal's true maximum]
 *    AND BY CONSTRUCTION CANNOT: R10 removed the replica deliberately, and `24 §3` K11's
 *    DECLARED INPUTS CONTAIN NO CONTROL-DATABASE READ."
 *
 * Three kinds of assertion below, and all three are needed:
 *
 *   1. THE STORES ARE DIFFERENT INSTANCES — asserted against `pg_control_system()`'s
 *      system identifier and the listening port, not against two URL strings differing.
 *   2. THE SOURCE CANNOT REACH ACROSS — no file under `src/audit/` names the control URL,
 *      a control repository, or a control table.
 *   3. THE RUNTIME DOES NOT NEED TO — the evaluator is run with the control database
 *      unreachable and every check still works.
 * =================================================================================
 */

let fixture: ReplicationFixture;
let kernel: LocalAuthorityHarness;

const T0 = new Date('2026-01-05T12:00:00.000Z');
const at = (minutes: number): Date => new Date(T0.getTime() + minutes * 60_000);

beforeAll(async () => {
  fixture = await createReplicationFixture();
});

afterAll(async () => {
  await fixture.close();
});

beforeEach(async () => {
  await fixture.reset();
  const client = await fixture.control.connect();
  try {
    await loadCommerceFixture(client);
    await loadS1eOrders(client);
    await loadAuthorityWorld(client);
  } finally {
    client.release();
  }
  kernel = makeLocalAuthorityHarness(fixture.control);
});

// =====================================================================================
// 1. Two instances.
// =====================================================================================

describe('the audit store is a DIFFERENT PostgreSQL instance', () => {
  it('the two servers report different system identifiers', async () => {
    const identity = async (
      connect: () => Promise<import('../../../src/db/pool.js').Client>,
    ): Promise<{ system_identifier: string; port: string; db: string }> => {
      const client = await connect();
      try {
        const result = await client.query<{
          system_identifier: string;
          port: string;
          db: string;
        }>(
          `SELECT (SELECT system_identifier FROM pg_control_system())::TEXT AS system_identifier,
                  current_setting('port') AS port,
                  current_database() AS db`,
        );
        return result.rows[0]!;
      } finally {
        client.release();
      }
    };
    const control = await identity(() => fixture.control.connect());
    const audit = await identity(() => fixture.audit.owner.connect());

    // A different CLUSTER, not a second schema wearing a different name. The system
    // identifier is generated by `initdb` and is the strongest available statement that
    // these are two distinct PostgreSQL clusters.
    expect(audit.system_identifier).not.toBe(control.system_identifier);
    expect(audit.db).not.toBe(control.db);

    // The two are reached at different endpoints. `current_setting('port')` is NOT the
    // discriminator: both containers listen on 5432 inside their own network namespace,
    // and it is the PUBLISHED port that differs — which is a property of the two URLs the
    // planes actually connect to.
    expect(new URL(fixture.audit.url).port).not.toBe(new URL(fixture.control.url).port);
  });

  it('the control tables do not exist on the audit server, and vice versa', async () => {
    const tables = async (
      connect: () => Promise<import('../../../src/db/pool.js').Client>,
    ): Promise<string[]> => {
      const client = await connect();
      try {
        const result = await client.query<{ table_name: string }>(
          `SELECT table_name FROM information_schema.tables
            WHERE table_schema = 'public' ORDER BY table_name`,
        );
        return result.rows.map((r) => r.table_name);
      } finally {
        client.release();
      }
    };
    const control = await tables(() => fixture.control.connect());
    const audit = await tables(() => fixture.audit.owner.connect());

    expect(control).toContain('effect_journal');
    expect(control).not.toContain('audit_journal');
    expect(audit).toContain('audit_journal');
    expect(audit).not.toContain('effect_journal');
    expect(audit).not.toContain('effect');
    expect(audit).not.toContain('exposure_reservation');
    expect(audit).not.toContain('window_balance');

    // And the two migration ledgers are separate objects with separate names.
    expect(control).toContain('schema_migration');
    expect(audit).toContain('audit_schema_migration');
    expect(audit).not.toContain('schema_migration');
  });

  it('the two migration directories are disjoint, and neither runner sees the other', async () => {
    const controlFiles = await readdir(join(process.cwd(), 'src', 'db', 'migrations'));
    const auditFiles = await readdir(join(process.cwd(), 'src', 'audit', 'db', 'migrations'));
    expect(controlFiles.filter((f) => auditFiles.includes(f))).toEqual([]);
    expect(controlFiles.every((f) => /^\d{4}__/.test(f))).toBe(true);
    expect(auditFiles.every((f) => /^A\d{4}__/.test(f))).toBe(true);

    const auditRunner = await readFile(
      join(process.cwd(), 'src', 'audit', 'db', 'migrate.ts'),
      'utf8',
    );
    const runnerCode = auditRunner
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/(^|[^:])\/\/.*$/gm, '$1');
    expect(runnerCode).toContain("join(HERE, 'migrations')");
    expect(runnerCode).not.toContain('controlUrl');
    expect(runnerCode).toContain('audit_schema_migration');
  });
});

// =====================================================================================
// 2. The source cannot reach across.
// =====================================================================================

describe('no audit-plane module can read the control database', () => {
  const FORBIDDEN: readonly (readonly [RegExp, string])[] = [
    [/\bcontrolUrl\b/, 'the control connection factory'],
    [/ACOS_CONTROL_PG_URL/, 'the control connection string'],
    [/\beffect_journal\b/, 'the control journal table'],
    [/\bjournal_counter\b/, 'the control sequence allocator'],
    [/\bwindow_balance\b/, 'the control exposure ledger'],
    [/\bexposure_reservation\b/, 'the control reservation table'],
    [/\bmirrored_at\b/, 'the control plane advisory column'],
    [/from '.*kernel\//, 'a control-plane kernel module'],
    [/from '.*db\/migrate/, 'the control migration runner'],
  ];

  it('every file under `src/audit/` is clean', async () => {
    const offenders: string[] = [];
    const walk = async (dir: string): Promise<void> => {
      for (const entry of await readdir(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(path);
          continue;
        }
        if (!entry.name.endsWith('.ts') && !entry.name.endsWith('.sql')) continue;
        const source = await readFile(path, 'utf8');
        // Comments are stripped: the files DISCUSS the control plane at length, and what
        // must be absent is a reference the runtime could follow.
        const code = source
          .replace(/\/\*[\s\S]*?\*\//g, '')
          .replace(/(^|[^:])\/\/.*$/gm, '$1')
          .replace(/^\s*--.*$/gm, '');
        for (const [pattern, what] of FORBIDDEN) {
          if (pattern.test(code)) offenders.push(`${path}: ${what} (${String(pattern)})`);
        }
      }
    };
    await walk(join(process.cwd(), 'src', 'audit'));
    expect(offenders, `an audit-plane module reaches the control plane:\n  ${offenders.join('\n  ')}`).toEqual(
      [],
    );
  });

  it('the audit plane imports EXACTLY ONE thing from the control tree: a connection factory', async () => {
    // `src/db/pool.ts` is generic infrastructure — `createPool`, `inTransaction`, and the
    // NUMERIC-as-string guard. The audit plane uses it for its OWN url. That is the whole
    // dependency, and it is asserted so a later import cannot slip in beside it.
    // `inTransaction` is added by S1H and is named in this test's OWN comment above as part
    // of what makes `pool.ts` generic infrastructure. `src/audit/mirrorInputStall.ts` uses it
    // to open ONE AUDIT transaction — `30 §5.7.1`'s issuance — and `inTransaction` takes a
    // client, so it cannot introduce a connection to anything. The property this test
    // protects is that the audit plane opens no CONTROL connection, and `controlUrl`,
    // `ACOS_CONTROL_PG_URL` and every control repository remain absent, asserted above.
    const permitted = new Set([
      'createPool',
      'auditUrl',
      'inTransaction',
      'Client',
      'Pool',
    ]);
    const offenders: string[] = [];
    const walk = async (dir: string): Promise<void> => {
      for (const entry of await readdir(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(path);
          continue;
        }
        if (!entry.name.endsWith('.ts')) continue;
        const source = await readFile(path, 'utf8');
        for (const match of source.matchAll(
          /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+'([^']*db\/pool\.js)'/g,
        )) {
          for (const name of match[1]!.split(',')) {
            const clean = name.replace(/\btype\b/, '').trim();
            if (clean !== '' && !permitted.has(clean)) offenders.push(`${path}: ${clean}`);
          }
        }
      }
    };
    await walk(join(process.cwd(), 'src', 'audit'));
    expect(offenders).toEqual([]);
  });

  it('and the audit plane holds no vendor credential and makes no outbound call — I8 is OPEN', async () => {
    // `37` S3 provisions the audit plane's own read-only vendor credentials. `37` S1 says
    // `I8` "proves nothing" until then. Asserted as an absence.
    const offenders: string[] = [];
    const walk = async (dir: string): Promise<void> => {
      for (const entry of await readdir(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(path);
          continue;
        }
        const source = await readFile(path, 'utf8');
        for (const forbidden of ['https://', 'fetch(', 'axios', 'node:http']) {
          if (source.includes(forbidden)) offenders.push(`${path}: ${forbidden}`);
        }
      }
    };
    await walk(join(process.cwd(), 'src', 'audit'));
    expect(offenders).toEqual([]);
  });

  it('the two planes agree on the cadence by TRANSCRIPTION, not by import', async () => {
    // Both constants come from `30 §5.4`. Neither module imports the other's.
    expect(ATTESTATION_CADENCE_MS * ATTESTATION_K).toBe(ATTESTATION_STALL_BOUND_MS);
    const auditSource = await readFile(
      join(process.cwd(), 'src', 'audit', 'transportCompleteness.ts'),
      'utf8',
    );
    expect(auditSource).not.toContain('replication/attestation');
  });
});

// =====================================================================================
// 3. The runtime does not need the control plane at all.
// =====================================================================================

describe('the evaluator works with the control database unreachable', () => {
  it('every check still runs, and the tail-truncation case is still detected', async () => {
    const spec = s1eSpec({ admittedResourceRefs: [S1E_PASS_ORDER.resourceRef, CAN03.resourceRef] });
    await proposeAndAuthorise(kernel, S1E_PASS_ORDER, { spec });
    await proposeAndAuthorise(kernel, CAN03, { spec });
    await emitAttestation(fixture.control.pool, COMPANY_ID, at(0)); // seq 3, attests max 2
    await emitAttestation(fixture.control.pool, COMPANY_ID, at(5)); // seq 4, attests max 3

    for (const seq of [1n, 2n, 4n]) {
      await fixture.ingress.ingest(await transportRecordFor(fixture, seq));
    }

    // THE CONTROL PLANE GOES AWAY ENTIRELY.
    await fixture.control.close();
    let report;
    try {
      report = await evaluateTransportCompleteness(fixture.audit.evaluator, COMPANY_ID, at(6));
    } finally {
      fixture = await createReplicationFixture();
    }

    const kinds = report.findings.map((f) => f.kind);
    expect(kinds).toContain('AUDIT_COMPLETENESS_GAP'); // seq 3 missing
    expect(kinds).toContain('ATTESTATION_INCONSISTENT'); // below the attested max
    expect(report.heldSequences).toEqual([1n, 2n, 4n]);
  });
});
