import { describe, expect, it } from 'vitest';

import {
  classifyDispatchPrecedence,
  type PrecedenceOperands,
} from '../../src/kernel/mirror/dispatchPrecedence.js';
import type { ActionClass, Recoverability } from '../../src/kernel/canonicalisation/actionCatalogue.js';
import { money } from '../../src/kernel/exposure/money.js';
import {
  ORACLE_STATES,
  PERMISSIVENESS,
  allOracleCases,
  expectedFor,
  type OracleCase,
  type OracleState,
} from '../support/mirrorPrecedenceTable.js';

/**
 * `VC-A2` — THE INVERSION PROOF, AND THE CORROBORATION RELAXATION PROOF.
 *
 * =================================================================================
 * `36 §9`, VC-A2, verbatim:
 *
 *   "**VC-A2 — the mirror machine is inverted.** In `UNCORROBORATED_STALL`, a clock-bearing
 *    COMPENSABLE effect **suspends**; in `NORMAL` and `CORROBORATED_DEGRADED` it dispatches.
 *    **Path B end-to-end:** a control plane unilaterally declaring degradation must find
 *    itself **stricter**, not looser — assert the refund it wanted to dispatch is suspended."
 *
 * `§23` of the S1H mandate: "Reproduce the load-bearing inversion proof across **every
 * currently admissible recoverability class/clock/approval combination**. [...] Generate the
 * cross-product from an independently declared test table and compare to hand-authored
 * expected dispositions."
 *
 * `§39`: "Forbidden: expected precedence generated by production rule list."
 *
 * THE CROSS-PRODUCT AND ITS EXPECTATIONS BOTH COME FROM `tests/support/
 * mirrorPrecedenceTable.ts`, which imports nothing from `src/`. Production is called once
 * per row and compared.
 * =================================================================================
 */

const ACTION_FOR: Readonly<Record<Recoverability, ActionClass>> = {
  // `26 §5`'s worked assignments, as the accepted catalogue records them.
  REVERSIBLE: 'campaign.pause',
  COMPENSABLE: 'refund.create',
  IRRECOVERABLE: 'fulfilment.reship',
};

const NOW = new Date('2026-03-01T12:00:00.000Z');

function operands(state: OracleState, c: OracleCase): PrecedenceOperands {
  return {
    mirrorState: state,
    actionClass: ACTION_FOR[c.recoverability],
    recoverability: c.recoverability,
    clockBearing: c.clockBearing,
    // v1.3.3: the DECLARED OPERAND, not a boolean. `51 §3.7` makes it
    // `exposure.total_exposure` and production derives the above-floor predicate from it, so
    // this suite now proves the derivation as well as the truth table (`S1H-C1`).
    totalExposure: money(c.totalExposure),
    hasRecordedApproval: c.hasRecordedApproval,
    // NO OVERRIDE anywhere in this file. `§23`'s inversion is a property of the states
    // themselves; the override is `VC-A2e`'s subject and admitting one here would make the
    // inversion table depend on a grant.
    activeOverride: null,
    // `30 §5.1a`'s `continuous_unreachability` operand. Non-null exactly when a degraded
    // state holds, and DELIBERATELY WELL INSIDE the 30-minute threshold: the FULL-HALT
    // POSTURE is `full-halt-posture.test.ts`'s subject and admitting it here would collapse
    // the inversion table onto HALT and make the inversion proof vacuous.
    unreachableSince: state === 'NORMAL' ? null : new Date(NOW.getTime() - 60_000),
    now: NOW,
  };
}

function label(c: OracleCase): string {
  return (
    `${c.recoverability}` +
    `/clock=${String(c.clockBearing)}` +
    `/exposure=${c.totalExposure}` +
    `/approved=${String(c.hasRecordedApproval)}`
  );
}

const CASES = allOracleCases();

describe('the cross-product is complete and non-degenerate', () => {
  it('24 operand combinations × 3 states = 72 rows', () => {
    // Stated as arithmetic so a future edit that drops an operand dimension fails here
    // rather than silently narrowing every proof below.
    expect(CASES).toHaveLength(24);
    expect(ORACLE_STATES).toHaveLength(3);
    expect(CASES.length * ORACLE_STATES.length).toBe(72);
  });

  it('and the oracle disagrees with itself across states somewhere — it is not a constant', () => {
    // `51 §7`: "A differential oracle with nothing to disagree about proves nothing." If the
    // hand-authored table gave the same disposition in every state, the inversion proof below
    // would pass vacuously.
    const differing = CASES.filter((c) => {
      const normal = expectedFor('NORMAL', c).disposition;
      return ORACLE_STATES.some((s) => expectedFor(s, c).disposition !== normal);
    });
    expect(differing.length).toBeGreaterThan(0);
  });
});

describe('production matches the HAND-AUTHORED table, row by row, including the matched row', () => {
  for (const state of ORACLE_STATES) {
    for (const c of CASES) {
      it(`${state} — ${label(c)}`, () => {
        const expected = expectedFor(state, c);
        const actual = classifyDispatchPrecedence(operands(state, c));
        expect(actual.disposition).toBe(expected.disposition);
        // `VC-A6` asserts WHICH row decided, not only the outcome: the right answer for the
        // wrong reason is how an unordered implementation passes an outcome-only test.
        expect(actual.matchedRow).toBe(expected.row);
        expect(actual.requiresUnmirroredTag).toBe(expected.requiresUnmirroredTag);
      });
    }
  }
});

describe('`VC-A2` — A UNILATERAL CONTROL-SIDE DECLARATION NEVER INCREASES ELIGIBILITY', () => {
  it('for every one of the 24 combinations, UNCORROBORATED_STALL is equal or STRICTER than NORMAL', () => {
    // THE LOAD-BEARING PROPERTY OF THE WHOLE SLICE. `30 §5.6`: "There is no longer anything
    // to gain by lying, so the transition does not need to be gated against a lie."
    //
    // The comparison is over `PERMISSIVENESS`, which is declared in the oracle file from
    // `30 §5.1`'s own row texts and not from any production enum's declaration order.
    const morePermissive: string[] = [];
    for (const c of CASES) {
      const normal = classifyDispatchPrecedence(operands('NORMAL', c));
      const stall = classifyDispatchPrecedence(operands('UNCORROBORATED_STALL', c));
      if (PERMISSIVENESS[stall.disposition] > PERMISSIVENESS[normal.disposition]) {
        morePermissive.push(
          `${label(c)}: NORMAL=${normal.disposition} UNCORROBORATED=${stall.disposition}`,
        );
      }
    }
    expect(
      morePermissive,
      'a unilateral control-side stall declaration became MORE permissive:\n  ' +
        morePermissive.join('\n  '),
    ).toEqual([]);
  });

  it('and it is STRICTLY stricter for at least one row — the inversion does real work', () => {
    // If no row became stricter, the previous assertion would hold trivially and the
    // inversion would be decorative. `30 §5.1` row 3 is the row: "In `UNCORROBORATED_STALL`,
    // suspend — **this row is the inversion**."
    const stricter = CASES.filter((c) => {
      const normal = classifyDispatchPrecedence(operands('NORMAL', c));
      const stall = classifyDispatchPrecedence(operands('UNCORROBORATED_STALL', c));
      return PERMISSIVENESS[stall.disposition] < PERMISSIVENESS[normal.disposition];
    });
    expect(stricter.length).toBeGreaterThan(0);
    // And every one of them is row 3, because row 3 is the only row whose behaviour differs
    // between `NORMAL` and `UNCORROBORATED_STALL` in `22 §3.1`'s table.
    for (const c of stricter) {
      expect(classifyDispatchPrecedence(operands('NORMAL', c)).matchedRow).toBe(3);
      expect(c.recoverability).toBe('COMPENSABLE');
      expect(c.clockBearing).toBe(true);
    }
  });

  it('the above-floor refund case specifically: NORMAL dispatches, UNCORROBORATED suspends', () => {
    // `36 §9` VC-A6's fixture and `22 §3.1`'s worked case, as one row: above the floor,
    // clock-bearing, COMPENSABLE, approved. `30 §5.1`: "An above-floor clock-bearing
    // COMPENSABLE effect [...] reaches row 3 and dispatches."
    //
    // v1.3.3 re-bases the amount. `36`'s VC-A6 now reads "a **$22.00 refund inside a live
    // FTC clock** — above the declared `$20.00` approval floor (`51 §3.7`) and still
    // admitted by `refund.create`'s `$25.00` `per_action_max`", because the old `$30`
    // fixture is inadmissible: `26 §8` denies `PER_ACTION` above `$25.00` and a denied
    // effect never reaches this classifier at all.
    const refund: OracleCase = {
      recoverability: 'COMPENSABLE',
      clockBearing: true,
      totalExposure: '22.00',
      hasRecordedApproval: true,
    };
    const normal = classifyDispatchPrecedence(operands('NORMAL', refund));
    expect(normal.matchedRow).toBe(3);
    expect(normal.disposition).toBe('DISPATCH_ELIGIBLE');

    const stall = classifyDispatchPrecedence(operands('UNCORROBORATED_STALL', refund));
    expect(stall.matchedRow).toBe(3);
    expect(stall.disposition).toBe('SUSPEND');
    // "the only escape is a `DegradedModeOverride` scoped to this row (§5.7.2)".
    expect(stall.ownerOverrideAvailable).toBe(true);
  });
});

describe('`VC-A2` — ONLY THE DECLARED ROWS RELAX IN CORROBORATED_DEGRADED', () => {
  it('CORROBORATED_DEGRADED is never stricter than NORMAL, and never looser either', () => {
    // `36 §6`: "`CORROBORATED_DEGRADED`: **as `NORMAL`**, with every dispatch tagged
    // `DISPATCHED_UNMIRRORED`." So the dispositions must be IDENTICAL to `NORMAL`'s and only
    // the tag differs. `§24` of the mandate: "Only the architecture-declared rows may become
    // less restrictive. No others."
    for (const c of CASES) {
      const normal = classifyDispatchPrecedence(operands('NORMAL', c));
      const corroborated = classifyDispatchPrecedence(operands('CORROBORATED_DEGRADED', c));
      expect(corroborated.disposition, label(c)).toBe(normal.disposition);
      expect(corroborated.matchedRow, label(c)).toBe(normal.matchedRow);
    }
  });

  it('exactly the rows that relax from UNCORROBORATED are the clock-bearing COMPENSABLE ones', () => {
    const relaxed = CASES.filter((c) => {
      const stall = classifyDispatchPrecedence(operands('UNCORROBORATED_STALL', c));
      const corroborated = classifyDispatchPrecedence(operands('CORROBORATED_DEGRADED', c));
      return PERMISSIVENESS[corroborated.disposition] > PERMISSIVENESS[stall.disposition];
    });
    expect(relaxed.length).toBeGreaterThan(0);
    for (const c of relaxed) {
      expect(c.recoverability).toBe('COMPENSABLE');
      expect(c.clockBearing).toBe(true);
      expect(classifyDispatchPrecedence(operands('CORROBORATED_DEGRADED', c)).matchedRow).toBe(3);
    }
  });

  it('every dispatch in CORROBORATED_DEGRADED requires the `DISPATCHED_UNMIRRORED` tag', () => {
    // `36 §6`: "with **every** dispatch tagged". Not only row 3 — row 5's REVERSIBLE dispatch
    // too, because `I17f(c)` quantifies over every effect inside a published stall interval.
    for (const c of CASES) {
      const d = classifyDispatchPrecedence(operands('CORROBORATED_DEGRADED', c));
      if (d.disposition === 'DISPATCH_ELIGIBLE') {
        expect(d.requiresUnmirroredTag, label(c)).toBe(true);
      } else {
        expect(d.requiresUnmirroredTag, label(c)).toBe(false);
      }
    }
  });

  it('and NOTHING is tagged in NORMAL or UNCORROBORATED_STALL', () => {
    // `I17f(a)`: "No effect carries `DISPATCHED_UNMIRRORED` **without** a concurrent
    // audit-plane `MIRROR_INPUT_STALL` interval covering its dispatch timestamp." In
    // `UNCORROBORATED_STALL` no published interval is KNOWN to exist — the signal is what
    // proves one does — so tagging there would risk violating (a). The residual, an effect
    // dispatched in `UNCORROBORATED_STALL` during a partition in which the audit plane DID
    // publish, is `S1H-result.md §10`'s `I17f(c)` partition case and is reported OPEN.
    for (const state of ['NORMAL', 'UNCORROBORATED_STALL'] as const) {
      for (const c of CASES) {
        expect(
          classifyDispatchPrecedence(operands(state, c)).requiresUnmirroredTag,
          `${state} ${label(c)}`,
        ).toBe(false);
      }
    }
  });
});

describe('the three-way table `§47 §6` asks for, computed once and asserted', () => {
  it('for every recoverability/clock/approval class, NORMAL ≥ CORROBORATED ≥ UNCORROBORATED', () => {
    // The single ordering statement the owner report's table rests on. Written as a chain so
    // a violation names which link broke.
    for (const c of CASES) {
      const n = PERMISSIVENESS[classifyDispatchPrecedence(operands('NORMAL', c)).disposition];
      const d =
        PERMISSIVENESS[classifyDispatchPrecedence(operands('CORROBORATED_DEGRADED', c)).disposition];
      const u =
        PERMISSIVENESS[classifyDispatchPrecedence(operands('UNCORROBORATED_STALL', c)).disposition];
      expect(n, `NORMAL vs CORROBORATED for ${label(c)}`).toBe(d);
      expect(u, `UNCORROBORATED must not exceed NORMAL for ${label(c)}`).toBeLessThanOrEqual(n);
    }
  });
});
